
//source: https://www.thebluealliance.com/api/v3/event/2020week0/matches
export const Matches = [
  {
    "actual_time": 1581796140,
    "alliances": {
      "blue": {
        "dq_team_keys": [],
        "score": 112,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc3117",
          "frc4041",
          "frc501"
        ]
      },
      "red": {
        "dq_team_keys": [],
        "score": 79,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc1153",
          "frc5962",
          "frc238"
        ]
      }
    },
    "comp_level": "f",
    "event_key": "2020week0",
    "key": "2020week0_f1m1",
    "match_number": 1,
    "post_result_time": 1581796502,
    "predicted_time": 1581796442,
    "score_breakdown": {
      "blue": {
        "adjustPoints": 0,
        "autoCellPoints": 14,
        "autoCellsBottom": 0,
        "autoCellsInner": 1,
        "autoCellsOuter": 2,
        "autoInitLinePoints": 15,
        "autoPoints": 29,
        "controlPanelPoints": 0,
        "endgamePoints": 30,
        "endgameRobot1": "Park",
        "endgameRobot2": "None",
        "endgameRobot3": "Hang",
        "endgameRungIsLevel": "NotLevel",
        "foulCount": 0,
        "foulPoints": 24,
        "initLineRobot1": "Exited",
        "initLineRobot2": "Exited",
        "initLineRobot3": "Exited",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": true,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 1,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 1,
        "teleopCellPoints": 29,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 1,
        "teleopCellsOuter": 13,
        "teleopPoints": 59,
        "totalPoints": 112
      },
      "red": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 10,
        "autoPoints": 10,
        "controlPanelPoints": 0,
        "endgamePoints": 45,
        "endgameRobot1": "Park",
        "endgameRobot2": "Hang",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 3,
        "foulPoints": 15,
        "initLineRobot1": "Exited",
        "initLineRobot2": "Exited",
        "initLineRobot3": "None",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 1,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 1,
        "teleopCellPoints": 9,
        "teleopCellsBottom": 5,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 2,
        "teleopPoints": 54,
        "totalPoints": 79
      }
    },
    "set_number": 1,
    "time": 1581794460,
    "videos": [],
    "winning_alliance": "blue"
  },
  {
    "actual_time": 1581797289,
    "alliances": {
      "blue": {
        "dq_team_keys": [],
        "score": 146,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc3117",
          "frc4041",
          "frc501"
        ]
      },
      "red": {
        "dq_team_keys": [],
        "score": 98,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc1153",
          "frc5962",
          "frc238"
        ]
      }
    },
    "comp_level": "f",
    "event_key": "2020week0",
    "key": "2020week0_f1m2",
    "match_number": 2,
    "post_result_time": 1581797698,
    "predicted_time": 1581797641,
    "score_breakdown": {
      "blue": {
        "adjustPoints": 0,
        "autoCellPoints": 14,
        "autoCellsBottom": 0,
        "autoCellsInner": 1,
        "autoCellsOuter": 2,
        "autoInitLinePoints": 15,
        "autoPoints": 29,
        "controlPanelPoints": 0,
        "endgamePoints": 50,
        "endgameRobot1": "Park",
        "endgameRobot2": "Park",
        "endgameRobot3": "Hang",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 15,
        "initLineRobot1": "Exited",
        "initLineRobot2": "Exited",
        "initLineRobot3": "Exited",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": true,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 1,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 52,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 2,
        "teleopCellsOuter": 23,
        "teleopPoints": 102,
        "totalPoints": 146
      },
      "red": {
        "adjustPoints": 0,
        "autoCellPoints": 8,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 2,
        "autoInitLinePoints": 15,
        "autoPoints": 23,
        "controlPanelPoints": 0,
        "endgamePoints": 50,
        "endgameRobot1": "Park",
        "endgameRobot2": "Hang",
        "endgameRobot3": "Park",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "Exited",
        "initLineRobot2": "Exited",
        "initLineRobot3": "Exited",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": true,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 1,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 1,
        "teleopCellPoints": 25,
        "teleopCellsBottom": 17,
        "teleopCellsInner": 2,
        "teleopCellsOuter": 1,
        "teleopPoints": 75,
        "totalPoints": 98
      }
    },
    "set_number": 1,
    "time": 1581794880,
    "videos": [],
    "winning_alliance": "blue"
  },
  {
    "actual_time": 1581787595,
    "alliances": {
      "blue": {
        "dq_team_keys": [],
        "score": 39,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc4909",
          "frc151",
          "frc4905"
        ]
      },
      "red": {
        "dq_team_keys": [],
        "score": 52,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc5687",
          "frc1519",
          "frc1721"
        ]
      }
    },
    "comp_level": "qf",
    "event_key": "2020week0",
    "key": "2020week0_qf1m1",
    "match_number": 1,
    "post_result_time": 1581787784,
    "predicted_time": 1581787564,
    "score_breakdown": {
      "blue": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 5,
        "autoPoints": 5,
        "controlPanelPoints": 0,
        "endgamePoints": 30,
        "endgameRobot1": "Park",
        "endgameRobot2": "None",
        "endgameRobot3": "Hang",
        "endgameRungIsLevel": "NotLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "None",
        "initLineRobot2": "None",
        "initLineRobot3": "Exited",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 1,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 4,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 2,
        "teleopPoints": 34,
        "totalPoints": 39
      },
      "red": {
        "adjustPoints": 0,
        "autoCellPoints": 8,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 2,
        "autoInitLinePoints": 10,
        "autoPoints": 18,
        "controlPanelPoints": 0,
        "endgamePoints": 10,
        "endgameRobot1": "Park",
        "endgameRobot2": "Park",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "Exited",
        "initLineRobot2": "Exited",
        "initLineRobot3": "None",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": true,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 24,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 2,
        "teleopCellsOuter": 9,
        "teleopPoints": 34,
        "totalPoints": 52
      }
    },
    "set_number": 1,
    "time": 1581786900,
    "videos": [
      {
        "key": "wq0lucTSG5E",
        "type": "youtube"
      }
    ],
    "winning_alliance": "red"
  },
  {
    "actual_time": 1581789675,
    "alliances": {
      "blue": {
        "dq_team_keys": [],
        "score": 68,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc4909",
          "frc151",
          "frc4905"
        ]
      },
      "red": {
        "dq_team_keys": [],
        "score": 86,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc5687",
          "frc1519",
          "frc1721"
        ]
      }
    },
    "comp_level": "qf",
    "event_key": "2020week0",
    "key": "2020week0_qf1m2",
    "match_number": 2,
    "post_result_time": 1581789861,
    "predicted_time": 1581789724,
    "score_breakdown": {
      "blue": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 5,
        "autoPoints": 5,
        "controlPanelPoints": 0,
        "endgamePoints": 45,
        "endgameRobot1": "None",
        "endgameRobot2": "Park",
        "endgameRobot3": "Hang",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "None",
        "initLineRobot2": "None",
        "initLineRobot3": "Exited",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": true,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 1,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 1,
        "teleopCellPoints": 18,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 9,
        "teleopPoints": 63,
        "totalPoints": 68
      },
      "red": {
        "adjustPoints": 0,
        "autoCellPoints": 12,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 3,
        "autoInitLinePoints": 10,
        "autoPoints": 22,
        "controlPanelPoints": 0,
        "endgamePoints": 30,
        "endgameRobot1": "Park",
        "endgameRobot2": "Hang",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "NotLevel",
        "foulCount": 0,
        "foulPoints": 15,
        "initLineRobot1": "Exited",
        "initLineRobot2": "Exited",
        "initLineRobot3": "None",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": true,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 1,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 19,
        "teleopCellsBottom": 1,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 9,
        "teleopPoints": 49,
        "totalPoints": 86
      }
    },
    "set_number": 1,
    "time": 1581788580,
    "videos": [
      {
        "key": "bOTguoPAtN0",
        "type": "youtube"
      }
    ],
    "winning_alliance": "red"
  },
  {
    "actual_time": 1581788051,
    "alliances": {
      "blue": {
        "dq_team_keys": [],
        "score": 55,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc1153",
          "frc5962",
          "frc238"
        ]
      },
      "red": {
        "dq_team_keys": [],
        "score": 42,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc296",
          "frc3467",
          "frc3986"
        ]
      }
    },
    "comp_level": "qf",
    "event_key": "2020week0",
    "key": "2020week0_qf2m1",
    "match_number": 1,
    "post_result_time": 1581788231,
    "predicted_time": 1581788164,
    "score_breakdown": {
      "blue": {
        "adjustPoints": 0,
        "autoCellPoints": 4,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 1,
        "autoInitLinePoints": 15,
        "autoPoints": 19,
        "controlPanelPoints": 0,
        "endgamePoints": 10,
        "endgameRobot1": "None",
        "endgameRobot2": "Park",
        "endgameRobot3": "Park",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "Exited",
        "initLineRobot2": "Exited",
        "initLineRobot3": "Exited",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": true,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 26,
        "teleopCellsBottom": 4,
        "teleopCellsInner": 2,
        "teleopCellsOuter": 8,
        "teleopPoints": 36,
        "totalPoints": 55
      },
      "red": {
        "adjustPoints": 0,
        "autoCellPoints": 6,
        "autoCellsBottom": 3,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 15,
        "autoPoints": 21,
        "controlPanelPoints": 0,
        "endgamePoints": 5,
        "endgameRobot1": "None",
        "endgameRobot2": "Park",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "Exited",
        "initLineRobot2": "Exited",
        "initLineRobot3": "Exited",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": true,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 16,
        "teleopCellsBottom": 4,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 6,
        "teleopPoints": 21,
        "totalPoints": 42
      }
    },
    "set_number": 2,
    "time": 1581787320,
    "videos": [],
    "winning_alliance": "blue"
  },
  {
    "actual_time": 1581790163,
    "alliances": {
      "blue": {
        "dq_team_keys": [],
        "score": 157,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc1153",
          "frc5962",
          "frc238"
        ]
      },
      "red": {
        "dq_team_keys": [],
        "score": 39,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc296",
          "frc3467",
          "frc3986"
        ]
      }
    },
    "comp_level": "qf",
    "event_key": "2020week0",
    "key": "2020week0_qf2m2",
    "match_number": 2,
    "post_result_time": 1581790418,
    "predicted_time": 1581790321,
    "score_breakdown": {
      "blue": {
        "adjustPoints": 0,
        "autoCellPoints": 4,
        "autoCellsBottom": 2,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 10,
        "autoPoints": 14,
        "controlPanelPoints": 0,
        "endgamePoints": 50,
        "endgameRobot1": "Park",
        "endgameRobot2": "Hang",
        "endgameRobot3": "Park",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 63,
        "initLineRobot1": "Exited",
        "initLineRobot2": "Exited",
        "initLineRobot3": "None",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": true,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 1,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 30,
        "teleopCellsBottom": 7,
        "teleopCellsInner": 1,
        "teleopCellsOuter": 10,
        "teleopPoints": 80,
        "totalPoints": 157
      },
      "red": {
        "adjustPoints": 0,
        "autoCellPoints": 6,
        "autoCellsBottom": 3,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 10,
        "autoPoints": 16,
        "controlPanelPoints": 0,
        "endgamePoints": 5,
        "endgameRobot1": "None",
        "endgameRobot2": "Park",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 1,
        "foulPoints": 0,
        "initLineRobot1": "Exited",
        "initLineRobot2": "Exited",
        "initLineRobot3": "None",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": true,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 4,
        "teleopCellPoints": 18,
        "teleopCellsBottom": 8,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 5,
        "teleopPoints": 23,
        "totalPoints": 39
      }
    },
    "set_number": 2,
    "time": 1581789000,
    "videos": [
      {
        "key": "yvNJV0Qk30A",
        "type": "youtube"
      }
    ],
    "winning_alliance": "blue"
  },
  {
    "actual_time": 1581788510,
    "alliances": {
      "blue": {
        "dq_team_keys": [],
        "score": 27,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc3323",
          "frc2713",
          "frc2342"
        ]
      },
      "red": {
        "dq_team_keys": [],
        "score": 13,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc1073",
          "frc811",
          "frc58"
        ]
      }
    },
    "comp_level": "qf",
    "event_key": "2020week0",
    "key": "2020week0_qf3m1",
    "match_number": 1,
    "post_result_time": 1581788712,
    "predicted_time": 1581788578,
    "score_breakdown": {
      "blue": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 5,
        "autoPoints": 5,
        "controlPanelPoints": 0,
        "endgamePoints": 10,
        "endgameRobot1": "Park",
        "endgameRobot2": "None",
        "endgameRobot3": "Park",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "None",
        "initLineRobot2": "None",
        "initLineRobot3": "Exited",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": true,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 12,
        "teleopCellsBottom": 12,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 0,
        "teleopPoints": 22,
        "totalPoints": 27
      },
      "red": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 0,
        "autoPoints": 0,
        "controlPanelPoints": 0,
        "endgamePoints": 5,
        "endgameRobot1": "Park",
        "endgameRobot2": "None",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "None",
        "initLineRobot2": "None",
        "initLineRobot3": "None",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 8,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 4,
        "teleopPoints": 13,
        "totalPoints": 13
      }
    },
    "set_number": 3,
    "time": 1581787740,
    "videos": [
      {
        "key": "3cDaVdNiSb4",
        "type": "youtube"
      }
    ],
    "winning_alliance": "blue"
  },
  {
    "actual_time": 1581790669,
    "alliances": {
      "blue": {
        "dq_team_keys": [],
        "score": 44,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc3323",
          "frc2713",
          "frc2342"
        ]
      },
      "red": {
        "dq_team_keys": [],
        "score": 73,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc1073",
          "frc811",
          "frc58"
        ]
      }
    },
    "comp_level": "qf",
    "event_key": "2020week0",
    "key": "2020week0_qf3m2",
    "match_number": 2,
    "post_result_time": 1581790928,
    "predicted_time": 1581790682,
    "score_breakdown": {
      "blue": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 5,
        "autoPoints": 5,
        "controlPanelPoints": 0,
        "endgamePoints": 10,
        "endgameRobot1": "Park",
        "endgameRobot2": "None",
        "endgameRobot3": "Park",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 24,
        "initLineRobot1": "None",
        "initLineRobot2": "None",
        "initLineRobot3": "Exited",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 3,
        "teleopCellPoints": 5,
        "teleopCellsBottom": 5,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 0,
        "teleopPoints": 15,
        "totalPoints": 44
      },
      "red": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 5,
        "autoPoints": 5,
        "controlPanelPoints": 0,
        "endgamePoints": 5,
        "endgameRobot1": "Park",
        "endgameRobot2": "None",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 8,
        "foulPoints": 45,
        "initLineRobot1": "Exited",
        "initLineRobot2": "None",
        "initLineRobot3": "None",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": true,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 18,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 9,
        "teleopPoints": 23,
        "totalPoints": 73
      }
    },
    "set_number": 3,
    "time": 1581789420,
    "videos": [
      {
        "key": "VbGrhUgga1s",
        "type": "youtube"
      }
    ],
    "winning_alliance": "red"
  },
  {
    "actual_time": 1581791774,
    "alliances": {
      "blue": {
        "dq_team_keys": [],
        "score": 27,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc3323",
          "frc2713",
          "frc2342"
        ]
      },
      "red": {
        "dq_team_keys": [],
        "score": 65,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc1073",
          "frc811",
          "frc58"
        ]
      }
    },
    "comp_level": "qf",
    "event_key": "2020week0",
    "key": "2020week0_qf3m3",
    "match_number": 3,
    "post_result_time": 1581791973,
    "predicted_time": 1581791822,
    "score_breakdown": {
      "blue": {
        "adjustPoints": 0,
        "autoCellPoints": 2,
        "autoCellsBottom": 1,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 5,
        "autoPoints": 7,
        "controlPanelPoints": 0,
        "endgamePoints": 15,
        "endgameRobot1": "Park",
        "endgameRobot2": "Park",
        "endgameRobot3": "Park",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "None",
        "initLineRobot2": "None",
        "initLineRobot3": "Exited",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 3,
        "teleopCellPoints": 5,
        "teleopCellsBottom": 5,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 0,
        "teleopPoints": 20,
        "totalPoints": 27
      },
      "red": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 0,
        "autoPoints": 0,
        "controlPanelPoints": 0,
        "endgamePoints": 10,
        "endgameRobot1": "Park",
        "endgameRobot2": "None",
        "endgameRobot3": "Park",
        "endgameRungIsLevel": "NotLevel",
        "foulCount": 0,
        "foulPoints": 45,
        "initLineRobot1": "None",
        "initLineRobot2": "None",
        "initLineRobot3": "None",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 10,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 5,
        "teleopPoints": 20,
        "totalPoints": 65
      }
    },
    "set_number": 3,
    "time": 1581791100,
    "videos": [
      {
        "key": "r9-kZTLsMhE",
        "type": "youtube"
      }
    ],
    "winning_alliance": "red"
  },
  {
    "actual_time": 1581789135,
    "alliances": {
      "blue": {
        "dq_team_keys": [],
        "score": 17,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc2079",
          "frc246",
          "frc2084"
        ]
      },
      "red": {
        "dq_team_keys": [],
        "score": 85,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc3117",
          "frc4041",
          "frc501"
        ]
      }
    },
    "comp_level": "qf",
    "event_key": "2020week0",
    "key": "2020week0_qf4m1",
    "match_number": 1,
    "post_result_time": 1581789340,
    "predicted_time": 1581789181,
    "score_breakdown": {
      "blue": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 5,
        "autoPoints": 5,
        "controlPanelPoints": 0,
        "endgamePoints": 10,
        "endgameRobot1": "Park",
        "endgameRobot2": "Park",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "None",
        "initLineRobot2": "Exited",
        "initLineRobot3": "None",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 2,
        "teleopCellPoints": 2,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 1,
        "teleopPoints": 12,
        "totalPoints": 17
      },
      "red": {
        "adjustPoints": 0,
        "autoCellPoints": 20,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 5,
        "autoInitLinePoints": 15,
        "autoPoints": 35,
        "controlPanelPoints": 0,
        "endgamePoints": 10,
        "endgameRobot1": "Park",
        "endgameRobot2": "Park",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 30,
        "initLineRobot1": "Exited",
        "initLineRobot2": "Exited",
        "initLineRobot3": "Exited",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": true,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 10,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 5,
        "teleopPoints": 20,
        "totalPoints": 85
      }
    },
    "set_number": 4,
    "time": 1581788160,
    "videos": [
      {
        "key": "hQBBiDlWbA8",
        "type": "youtube"
      }
    ],
    "winning_alliance": "red"
  },
  {
    "actual_time": 1581791222,
    "alliances": {
      "blue": {
        "dq_team_keys": [],
        "score": 31,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc2079",
          "frc246",
          "frc2084"
        ]
      },
      "red": {
        "dq_team_keys": [],
        "score": 70,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc3117",
          "frc4041",
          "frc501"
        ]
      }
    },
    "comp_level": "qf",
    "event_key": "2020week0",
    "key": "2020week0_qf4m2",
    "match_number": 2,
    "post_result_time": 1581791409,
    "predicted_time": 1581791221,
    "score_breakdown": {
      "blue": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 5,
        "autoPoints": 5,
        "controlPanelPoints": 0,
        "endgamePoints": 5,
        "endgameRobot1": "Park",
        "endgameRobot2": "None",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 15,
        "initLineRobot1": "None",
        "initLineRobot2": "Exited",
        "initLineRobot3": "None",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 6,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 3,
        "teleopPoints": 11,
        "totalPoints": 31
      },
      "red": {
        "adjustPoints": 0,
        "autoCellPoints": 22,
        "autoCellsBottom": 0,
        "autoCellsInner": 1,
        "autoCellsOuter": 4,
        "autoInitLinePoints": 15,
        "autoPoints": 37,
        "controlPanelPoints": 0,
        "endgamePoints": 10,
        "endgameRobot1": "Park",
        "endgameRobot2": "None",
        "endgameRobot3": "Park",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "Exited",
        "initLineRobot2": "Exited",
        "initLineRobot3": "Exited",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": true,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 1,
        "teleopCellPoints": 23,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 3,
        "teleopCellsOuter": 7,
        "teleopPoints": 33,
        "totalPoints": 70
      }
    },
    "set_number": 4,
    "time": 1581789840,
    "videos": [
      {
        "key": "sd8fjuHdpNc",
        "type": "youtube"
      }
    ],
    "winning_alliance": "red"
  },
  {
    "actual_time": 1581774756,
    "alliances": {
      "blue": {
        "dq_team_keys": [],
        "score": 12,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc1721",
          "frc296",
          "frc151"
        ]
      },
      "red": {
        "dq_team_keys": [],
        "score": 5,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc5813",
          "frc2342",
          "frc3323"
        ]
      }
    },
    "comp_level": "qm",
    "event_key": "2020week0",
    "key": "2020week0_qm1",
    "match_number": 1,
    "post_result_time": 1581775014,
    "predicted_time": 1581774841,
    "score_breakdown": {
      "blue": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 5,
        "autoPoints": 5,
        "controlPanelPoints": 0,
        "endgamePoints": 0,
        "endgameRobot1": "None",
        "endgameRobot2": "None",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "None",
        "initLineRobot2": "Exited",
        "initLineRobot3": "None",
        "rp": 2,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 7,
        "teleopCellsBottom": 7,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 0,
        "teleopPoints": 7,
        "totalPoints": 12
      },
      "red": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 5,
        "autoPoints": 5,
        "controlPanelPoints": 0,
        "endgamePoints": 0,
        "endgameRobot1": "None",
        "endgameRobot2": "None",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "None",
        "initLineRobot2": "Exited",
        "initLineRobot3": "None",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 0,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 0,
        "teleopPoints": 0,
        "totalPoints": 5
      }
    },
    "set_number": 1,
    "time": 1581774300,
    "videos": [],
    "winning_alliance": "blue"
  },
  {
    "actual_time": 1581780546,
    "alliances": {
      "blue": {
        "dq_team_keys": [],
        "score": 41,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc5813",
          "frc5687",
          "frc1153"
        ]
      },
      "red": {
        "dq_team_keys": [],
        "score": 38,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc4905",
          "frc3117",
          "frc2084"
        ]
      }
    },
    "comp_level": "qm",
    "event_key": "2020week0",
    "key": "2020week0_qm10",
    "match_number": 10,
    "post_result_time": 1581780737,
    "predicted_time": 1581780659,
    "score_breakdown": {
      "blue": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 5,
        "autoPoints": 5,
        "controlPanelPoints": 0,
        "endgamePoints": 5,
        "endgameRobot1": "None",
        "endgameRobot2": "Park",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "None",
        "initLineRobot2": "None",
        "initLineRobot3": "Exited",
        "rp": 2,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": true,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 31,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 1,
        "teleopCellsOuter": 14,
        "teleopPoints": 36,
        "totalPoints": 41
      },
      "red": {
        "adjustPoints": 0,
        "autoCellPoints": 12,
        "autoCellsBottom": 0,
        "autoCellsInner": 2,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 5,
        "autoPoints": 17,
        "controlPanelPoints": 0,
        "endgamePoints": 10,
        "endgameRobot1": "Park",
        "endgameRobot2": "Park",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "None",
        "initLineRobot2": "Exited",
        "initLineRobot3": "None",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 11,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 1,
        "teleopCellsOuter": 4,
        "teleopPoints": 21,
        "totalPoints": 38
      }
    },
    "set_number": 1,
    "time": 1581779580,
    "videos": [
      {
        "key": "GnIhoHlaKcI",
        "type": "youtube"
      }
    ],
    "winning_alliance": "blue"
  },
  {
    "actual_time": 1581781060,
    "alliances": {
      "blue": {
        "dq_team_keys": [],
        "score": 34,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc246",
          "frc58",
          "frc296"
        ]
      },
      "red": {
        "dq_team_keys": [],
        "score": 5,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc151",
          "frc3986",
          "frc157"
        ]
      }
    },
    "comp_level": "qm",
    "event_key": "2020week0",
    "key": "2020week0_qm11",
    "match_number": 11,
    "post_result_time": 1581781238,
    "predicted_time": 1581781106,
    "score_breakdown": {
      "blue": {
        "adjustPoints": 0,
        "autoCellPoints": 6,
        "autoCellsBottom": 3,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 5,
        "autoPoints": 11,
        "controlPanelPoints": 0,
        "endgamePoints": 10,
        "endgameRobot1": "Park",
        "endgameRobot2": "Park",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "None",
        "initLineRobot2": "None",
        "initLineRobot3": "Exited",
        "rp": 2,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": true,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 13,
        "teleopCellsBottom": 11,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 1,
        "teleopPoints": 23,
        "totalPoints": 34
      },
      "red": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 0,
        "autoPoints": 0,
        "controlPanelPoints": 0,
        "endgamePoints": 5,
        "endgameRobot1": "Park",
        "endgameRobot2": "None",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "None",
        "initLineRobot2": "None",
        "initLineRobot3": "None",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 0,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 0,
        "teleopPoints": 5,
        "totalPoints": 5
      }
    },
    "set_number": 1,
    "time": 1581780120,
    "videos": [
      {
        "key": "lazLVP9AS4k",
        "type": "youtube"
      }
    ],
    "winning_alliance": "blue"
  },
  {
    "actual_time": 1581781531,
    "alliances": {
      "blue": {
        "dq_team_keys": [],
        "score": 41,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc2342",
          "frc4041",
          "frc3467"
        ]
      },
      "red": {
        "dq_team_keys": [],
        "score": 15,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc5962",
          "frc2713",
          "frc1729"
        ]
      }
    },
    "comp_level": "qm",
    "event_key": "2020week0",
    "key": "2020week0_qm12",
    "match_number": 12,
    "post_result_time": 1581781723,
    "predicted_time": 1581781623,
    "score_breakdown": {
      "blue": {
        "adjustPoints": 0,
        "autoCellPoints": 12,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 3,
        "autoInitLinePoints": 15,
        "autoPoints": 27,
        "controlPanelPoints": 0,
        "endgamePoints": 10,
        "endgameRobot1": "Park",
        "endgameRobot2": "Park",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 1,
        "foulPoints": 0,
        "initLineRobot1": "Exited",
        "initLineRobot2": "Exited",
        "initLineRobot3": "Exited",
        "rp": 2,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 4,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 2,
        "teleopPoints": 14,
        "totalPoints": 41
      },
      "red": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 5,
        "autoPoints": 5,
        "controlPanelPoints": 0,
        "endgamePoints": 5,
        "endgameRobot1": "Park",
        "endgameRobot2": "None",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 3,
        "initLineRobot1": "Exited",
        "initLineRobot2": "None",
        "initLineRobot3": "None",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 2,
        "teleopCellsBottom": 2,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 0,
        "teleopPoints": 7,
        "totalPoints": 15
      }
    },
    "set_number": 1,
    "time": 1581780660,
    "videos": [
      {
        "key": "MEBTit8I3hQ",
        "type": "youtube"
      }
    ],
    "winning_alliance": "blue"
  },
  {
    "actual_time": 1581782040,
    "alliances": {
      "blue": {
        "dq_team_keys": [],
        "score": 28,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc3323",
          "frc4909",
          "frc501"
        ]
      },
      "red": {
        "dq_team_keys": [],
        "score": 32,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc1519",
          "frc1073",
          "frc811"
        ]
      }
    },
    "comp_level": "qm",
    "event_key": "2020week0",
    "key": "2020week0_qm13",
    "match_number": 13,
    "post_result_time": 1581782335,
    "predicted_time": 1581782284,
    "score_breakdown": {
      "blue": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 0,
        "autoPoints": 0,
        "controlPanelPoints": 0,
        "endgamePoints": 5,
        "endgameRobot1": "Park",
        "endgameRobot2": "None",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 15,
        "initLineRobot1": "None",
        "initLineRobot2": "None",
        "initLineRobot3": "None",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 8,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 4,
        "teleopPoints": 13,
        "totalPoints": 28
      },
      "red": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 5,
        "autoPoints": 5,
        "controlPanelPoints": 0,
        "endgamePoints": 10,
        "endgameRobot1": "Park",
        "endgameRobot2": "Park",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "Exited",
        "initLineRobot2": "None",
        "initLineRobot3": "None",
        "rp": 2,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 1,
        "teleopCellPoints": 17,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 1,
        "teleopCellsOuter": 7,
        "teleopPoints": 27,
        "totalPoints": 32
      }
    },
    "set_number": 1,
    "time": 1581781200,
    "videos": [
      {
        "key": "AAiOZW2Tb0c",
        "type": "youtube"
      }
    ],
    "winning_alliance": "red"
  },
  {
    "actual_time": 1581782641,
    "alliances": {
      "blue": {
        "dq_team_keys": [],
        "score": 45,
        "surrogate_team_keys": [
          "frc4905",
          "frc1153"
        ],
        "team_keys": [
          "frc4905",
          "frc1153",
          "frc2079"
        ]
      },
      "red": {
        "dq_team_keys": [],
        "score": 30,
        "surrogate_team_keys": [
          "frc2713"
        ],
        "team_keys": [
          "frc238",
          "frc2713",
          "frc1721"
        ]
      }
    },
    "comp_level": "qm",
    "event_key": "2020week0",
    "key": "2020week0_qm14",
    "match_number": 14,
    "post_result_time": 1581782829,
    "predicted_time": 1581782761,
    "score_breakdown": {
      "blue": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 10,
        "autoPoints": 10,
        "controlPanelPoints": 0,
        "endgamePoints": 5,
        "endgameRobot1": "Park",
        "endgameRobot2": "None",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "Exited",
        "initLineRobot2": "Exited",
        "initLineRobot3": "None",
        "rp": 2,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": true,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 1,
        "teleopCellPoints": 30,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 15,
        "teleopPoints": 35,
        "totalPoints": 45
      },
      "red": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 0,
        "autoPoints": 0,
        "controlPanelPoints": 0,
        "endgamePoints": 15,
        "endgameRobot1": "Park",
        "endgameRobot2": "Park",
        "endgameRobot3": "Park",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 15,
        "initLineRobot1": "None",
        "initLineRobot2": "None",
        "initLineRobot3": "None",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 0,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 0,
        "teleopPoints": 15,
        "totalPoints": 30
      }
    },
    "set_number": 1,
    "time": 1581782040,
    "videos": [
      {
        "key": "7tzdK67QDFQ",
        "type": "youtube"
      }
    ],
    "winning_alliance": "blue"
  },
  {
    "actual_time": 1581775710,
    "alliances": {
      "blue": {
        "dq_team_keys": [],
        "score": 51,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc2084",
          "frc5962",
          "frc4041"
        ]
      },
      "red": {
        "dq_team_keys": [],
        "score": 10,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc4909",
          "frc238",
          "frc157"
        ]
      }
    },
    "comp_level": "qm",
    "event_key": "2020week0",
    "key": "2020week0_qm2",
    "match_number": 2,
    "post_result_time": 1581776149,
    "predicted_time": 1581775981,
    "score_breakdown": {
      "blue": {
        "adjustPoints": 0,
        "autoCellPoints": 12,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 3,
        "autoInitLinePoints": 5,
        "autoPoints": 17,
        "controlPanelPoints": 0,
        "endgamePoints": 30,
        "endgameRobot1": "None",
        "endgameRobot2": "Hang",
        "endgameRobot3": "Park",
        "endgameRungIsLevel": "NotLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "None",
        "initLineRobot2": "None",
        "initLineRobot3": "Exited",
        "rp": 2,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 1,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 4,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 2,
        "teleopPoints": 34,
        "totalPoints": 51
      },
      "red": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 5,
        "autoPoints": 5,
        "controlPanelPoints": 0,
        "endgamePoints": 5,
        "endgameRobot1": "None",
        "endgameRobot2": "None",
        "endgameRobot3": "Park",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "None",
        "initLineRobot2": "Exited",
        "initLineRobot3": "None",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 0,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 0,
        "teleopPoints": 5,
        "totalPoints": 10
      }
    },
    "set_number": 1,
    "time": 1581774900,
    "videos": [
      {
        "key": "D9Z3sMfO2yQ",
        "type": "youtube"
      }
    ],
    "winning_alliance": "blue"
  },
  {
    "actual_time": 1581776404,
    "alliances": {
      "blue": {
        "dq_team_keys": [],
        "score": 18,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc501",
          "frc1519",
          "frc5687"
        ]
      },
      "red": {
        "dq_team_keys": [],
        "score": 5,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc58",
          "frc2079",
          "frc1729"
        ]
      }
    },
    "comp_level": "qm",
    "event_key": "2020week0",
    "key": "2020week0_qm3",
    "match_number": 3,
    "post_result_time": 1581776677,
    "predicted_time": 1581776582,
    "score_breakdown": {
      "blue": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 5,
        "autoPoints": 5,
        "controlPanelPoints": 0,
        "endgamePoints": 5,
        "endgameRobot1": "None",
        "endgameRobot2": "Park",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 1,
        "foulPoints": 0,
        "initLineRobot1": "None",
        "initLineRobot2": "Exited",
        "initLineRobot3": "None",
        "rp": 2,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 8,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 4,
        "teleopPoints": 13,
        "totalPoints": 18
      },
      "red": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 0,
        "autoPoints": 0,
        "controlPanelPoints": 0,
        "endgamePoints": 0,
        "endgameRobot1": "None",
        "endgameRobot2": "None",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 3,
        "initLineRobot1": "None",
        "initLineRobot2": "None",
        "initLineRobot3": "None",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 2,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 1,
        "teleopPoints": 2,
        "totalPoints": 5
      }
    },
    "set_number": 1,
    "time": 1581775500,
    "videos": [
      {
        "key": "pGa2lpuxxPs",
        "type": "youtube"
      }
    ],
    "winning_alliance": "blue"
  },
  {
    "actual_time": 1581777186,
    "alliances": {
      "blue": {
        "dq_team_keys": [],
        "score": 15,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc1073",
          "frc3467",
          "frc2713"
        ]
      },
      "red": {
        "dq_team_keys": [],
        "score": 6,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc1153",
          "frc4905",
          "frc246"
        ]
      }
    },
    "comp_level": "qm",
    "event_key": "2020week0",
    "key": "2020week0_qm4",
    "match_number": 4,
    "post_result_time": 1581777387,
    "predicted_time": 1581777301,
    "score_breakdown": {
      "blue": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 0,
        "autoPoints": 0,
        "controlPanelPoints": 0,
        "endgamePoints": 5,
        "endgameRobot1": "None",
        "endgameRobot2": "Park",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "None",
        "initLineRobot2": "None",
        "initLineRobot3": "None",
        "rp": 2,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 10,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 5,
        "teleopPoints": 15,
        "totalPoints": 15
      },
      "red": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 0,
        "autoPoints": 0,
        "controlPanelPoints": 0,
        "endgamePoints": 0,
        "endgameRobot1": "None",
        "endgameRobot2": "None",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "None",
        "initLineRobot2": "None",
        "initLineRobot3": "None",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 6,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 3,
        "teleopPoints": 6,
        "totalPoints": 6
      }
    },
    "set_number": 1,
    "time": 1581776100,
    "videos": [
      {
        "key": "1Adk3dmj7oY",
        "type": "youtube"
      }
    ],
    "winning_alliance": "blue"
  },
  {
    "actual_time": 1581777714,
    "alliances": {
      "blue": {
        "dq_team_keys": [],
        "score": 10,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc3986",
          "frc1729",
          "frc238"
        ]
      },
      "red": {
        "dq_team_keys": [],
        "score": 16,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc3117",
          "frc811",
          "frc5813"
        ]
      }
    },
    "comp_level": "qm",
    "event_key": "2020week0",
    "key": "2020week0_qm5",
    "match_number": 5,
    "post_result_time": 1581777914,
    "predicted_time": 1581777873,
    "score_breakdown": {
      "blue": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 5,
        "autoPoints": 5,
        "controlPanelPoints": 0,
        "endgamePoints": 5,
        "endgameRobot1": "Park",
        "endgameRobot2": "None",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "None",
        "initLineRobot2": "None",
        "initLineRobot3": "Exited",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 0,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 0,
        "teleopPoints": 5,
        "totalPoints": 10
      },
      "red": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 5,
        "autoPoints": 5,
        "controlPanelPoints": 0,
        "endgamePoints": 5,
        "endgameRobot1": "None",
        "endgameRobot2": "Park",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "Exited",
        "initLineRobot2": "None",
        "initLineRobot3": "None",
        "rp": 2,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 6,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 3,
        "teleopPoints": 11,
        "totalPoints": 16
      }
    },
    "set_number": 1,
    "time": 1581776700,
    "videos": [
      {
        "key": "hfv_0IwJvh8",
        "type": "youtube"
      }
    ],
    "winning_alliance": "red"
  },
  {
    "actual_time": 1581778246,
    "alliances": {
      "blue": {
        "dq_team_keys": [],
        "score": 36,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc4041",
          "frc157",
          "frc4905"
        ]
      },
      "red": {
        "dq_team_keys": [],
        "score": 53,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc3323",
          "frc1153",
          "frc1519"
        ]
      }
    },
    "comp_level": "qm",
    "event_key": "2020week0",
    "key": "2020week0_qm6",
    "match_number": 6,
    "post_result_time": 1581778454,
    "predicted_time": 1581778344,
    "score_breakdown": {
      "blue": {
        "adjustPoints": 0,
        "autoCellPoints": 14,
        "autoCellsBottom": 0,
        "autoCellsInner": 1,
        "autoCellsOuter": 2,
        "autoInitLinePoints": 10,
        "autoPoints": 24,
        "controlPanelPoints": 0,
        "endgamePoints": 10,
        "endgameRobot1": "Park",
        "endgameRobot2": "None",
        "endgameRobot3": "Park",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "Exited",
        "initLineRobot2": "None",
        "initLineRobot3": "Exited",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 2,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 1,
        "teleopPoints": 12,
        "totalPoints": 36
      },
      "red": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 5,
        "autoPoints": 5,
        "controlPanelPoints": 0,
        "endgamePoints": 40,
        "endgameRobot1": "None",
        "endgameRobot2": "None",
        "endgameRobot3": "Hang",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "None",
        "initLineRobot2": "None",
        "initLineRobot3": "Exited",
        "rp": 2,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 1,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 8,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 4,
        "teleopPoints": 48,
        "totalPoints": 53
      }
    },
    "set_number": 1,
    "time": 1581777300,
    "videos": [
      {
        "key": "xA3UqG-xLHA",
        "type": "youtube"
      }
    ],
    "winning_alliance": "red"
  },
  {
    "actual_time": 1581778804,
    "alliances": {
      "blue": {
        "dq_team_keys": [],
        "score": 27,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc811",
          "frc246",
          "frc5962"
        ]
      },
      "red": {
        "dq_team_keys": [],
        "score": 26,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc5687",
          "frc1721",
          "frc58"
        ]
      }
    },
    "comp_level": "qm",
    "event_key": "2020week0",
    "key": "2020week0_qm7",
    "match_number": 7,
    "post_result_time": 1581779001,
    "predicted_time": 1581778861,
    "score_breakdown": {
      "blue": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 5,
        "autoPoints": 5,
        "controlPanelPoints": 0,
        "endgamePoints": 5,
        "endgameRobot1": "Park",
        "endgameRobot2": "None",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "None",
        "initLineRobot2": "None",
        "initLineRobot3": "Exited",
        "rp": 2,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": true,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 17,
        "teleopCellsBottom": 5,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 6,
        "teleopPoints": 22,
        "totalPoints": 27
      },
      "red": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 0,
        "autoPoints": 0,
        "controlPanelPoints": 0,
        "endgamePoints": 10,
        "endgameRobot1": "Park",
        "endgameRobot2": "None",
        "endgameRobot3": "Park",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "None",
        "initLineRobot2": "None",
        "initLineRobot3": "None",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 16,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 8,
        "teleopPoints": 26,
        "totalPoints": 26
      }
    },
    "set_number": 1,
    "time": 1581777900,
    "videos": [
      {
        "key": "hkdFOdWSB4Q",
        "type": "youtube"
      }
    ],
    "winning_alliance": "blue"
  },
  {
    "actual_time": 1581779506,
    "alliances": {
      "blue": {
        "dq_team_keys": [],
        "score": 15,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc2079",
          "frc1073",
          "frc3117"
        ]
      },
      "red": {
        "dq_team_keys": [],
        "score": 12,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc296",
          "frc2084",
          "frc2342"
        ]
      }
    },
    "comp_level": "qm",
    "event_key": "2020week0",
    "key": "2020week0_qm8",
    "match_number": 8,
    "post_result_time": 1581779704,
    "predicted_time": 1581779641,
    "score_breakdown": {
      "blue": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 5,
        "autoPoints": 5,
        "controlPanelPoints": 0,
        "endgamePoints": 10,
        "endgameRobot1": "Park",
        "endgameRobot2": "Park",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "None",
        "initLineRobot2": "None",
        "initLineRobot3": "Exited",
        "rp": 2,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 0,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 0,
        "teleopPoints": 10,
        "totalPoints": 15
      },
      "red": {
        "adjustPoints": 0,
        "autoCellPoints": 2,
        "autoCellsBottom": 1,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 5,
        "autoPoints": 7,
        "controlPanelPoints": 0,
        "endgamePoints": 5,
        "endgameRobot1": "Park",
        "endgameRobot2": "None",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "Exited",
        "initLineRobot2": "None",
        "initLineRobot3": "None",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 0,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 0,
        "teleopPoints": 5,
        "totalPoints": 12
      }
    },
    "set_number": 1,
    "time": 1581778500,
    "videos": [
      {
        "key": "EY2pitWfUTk",
        "type": "youtube"
      }
    ],
    "winning_alliance": "blue"
  },
  {
    "actual_time": 1581780089,
    "alliances": {
      "blue": {
        "dq_team_keys": [],
        "score": 12,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc2713",
          "frc151",
          "frc4909"
        ]
      },
      "red": {
        "dq_team_keys": [],
        "score": 9,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc3467",
          "frc501",
          "frc3986"
        ]
      }
    },
    "comp_level": "qm",
    "event_key": "2020week0",
    "key": "2020week0_qm9",
    "match_number": 9,
    "post_result_time": 1581780266,
    "predicted_time": 1581780072,
    "score_breakdown": {
      "blue": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 0,
        "autoPoints": 0,
        "controlPanelPoints": 0,
        "endgamePoints": 5,
        "endgameRobot1": "None",
        "endgameRobot2": "None",
        "endgameRobot3": "Park",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "None",
        "initLineRobot2": "None",
        "initLineRobot3": "None",
        "rp": 2,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 7,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 1,
        "teleopCellsOuter": 2,
        "teleopPoints": 12,
        "totalPoints": 12
      },
      "red": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 5,
        "autoPoints": 5,
        "controlPanelPoints": 0,
        "endgamePoints": 0,
        "endgameRobot1": "None",
        "endgameRobot2": "None",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "Exited",
        "initLineRobot2": "None",
        "initLineRobot3": "None",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 4,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 2,
        "teleopPoints": 4,
        "totalPoints": 9
      }
    },
    "set_number": 1,
    "time": 1581779040,
    "videos": [
      {
        "key": "I3CVp8KkJro",
        "type": "youtube"
      }
    ],
    "winning_alliance": "blue"
  },
  {
    "actual_time": 1581792512,
    "alliances": {
      "blue": {
        "dq_team_keys": [],
        "score": 95,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc1153",
          "frc5962",
          "frc238"
        ]
      },
      "red": {
        "dq_team_keys": [],
        "score": 58,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc5687",
          "frc1519",
          "frc1721"
        ]
      }
    },
    "comp_level": "sf",
    "event_key": "2020week0",
    "key": "2020week0_sf1m1",
    "match_number": 1,
    "post_result_time": 1581792717,
    "predicted_time": 1581792604,
    "score_breakdown": {
      "blue": {
        "adjustPoints": 0,
        "autoCellPoints": 8,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 2,
        "autoInitLinePoints": 15,
        "autoPoints": 23,
        "controlPanelPoints": 0,
        "endgamePoints": 45,
        "endgameRobot1": "None",
        "endgameRobot2": "Hang",
        "endgameRobot3": "Park",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "Exited",
        "initLineRobot2": "Exited",
        "initLineRobot3": "Exited",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": true,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 1,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 27,
        "teleopCellsBottom": 9,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 9,
        "teleopPoints": 72,
        "totalPoints": 95
      },
      "red": {
        "adjustPoints": 0,
        "autoCellPoints": 8,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 2,
        "autoInitLinePoints": 10,
        "autoPoints": 18,
        "controlPanelPoints": 0,
        "endgamePoints": 30,
        "endgameRobot1": "Park",
        "endgameRobot2": "Hang",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "NotLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "Exited",
        "initLineRobot2": "Exited",
        "initLineRobot3": "None",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 1,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 10,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 5,
        "teleopPoints": 40,
        "totalPoints": 58
      }
    },
    "set_number": 1,
    "time": 1581791940,
    "videos": [
      {
        "key": "QOo7UE2cghM",
        "type": "youtube"
      }
    ],
    "winning_alliance": "blue"
  },
  {
    "actual_time": 1581793877,
    "alliances": {
      "blue": {
        "dq_team_keys": [],
        "score": 87,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc1153",
          "frc5962",
          "frc238"
        ]
      },
      "red": {
        "dq_team_keys": [],
        "score": 82,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc5687",
          "frc1519",
          "frc1721"
        ]
      }
    },
    "comp_level": "sf",
    "event_key": "2020week0",
    "key": "2020week0_sf1m2",
    "match_number": 2,
    "post_result_time": 1581794110,
    "predicted_time": 1581794101,
    "score_breakdown": {
      "blue": {
        "adjustPoints": 0,
        "autoCellPoints": 8,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 2,
        "autoInitLinePoints": 10,
        "autoPoints": 18,
        "controlPanelPoints": 0,
        "endgamePoints": 15,
        "endgameRobot1": "Park",
        "endgameRobot2": "Park",
        "endgameRobot3": "Park",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 30,
        "initLineRobot1": "Exited",
        "initLineRobot2": "Exited",
        "initLineRobot3": "None",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": true,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 24,
        "teleopCellsBottom": 14,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 5,
        "teleopPoints": 39,
        "totalPoints": 87
      },
      "red": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 10,
        "autoPoints": 10,
        "controlPanelPoints": 0,
        "endgamePoints": 45,
        "endgameRobot1": "Park",
        "endgameRobot2": "Hang",
        "endgameRobot3": "None",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "Exited",
        "initLineRobot2": "Exited",
        "initLineRobot3": "None",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": true,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 1,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 2,
        "teleopCellPoints": 27,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 5,
        "teleopCellsOuter": 6,
        "teleopPoints": 72,
        "totalPoints": 82
      }
    },
    "set_number": 1,
    "time": 1581792780,
    "videos": [
      {
        "key": "Z9HZWCmKMqQ",
        "type": "youtube"
      }
    ],
    "winning_alliance": "blue"
  },
  {
    "actual_time": 1581793210,
    "alliances": {
      "blue": {
        "dq_team_keys": [],
        "score": 86,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc3117",
          "frc4041",
          "frc501"
        ]
      },
      "red": {
        "dq_team_keys": [],
        "score": 38,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc1073",
          "frc811",
          "frc58"
        ]
      }
    },
    "comp_level": "sf",
    "event_key": "2020week0",
    "key": "2020week0_sf2m1",
    "match_number": 1,
    "post_result_time": 1581793495,
    "predicted_time": 1581793441,
    "score_breakdown": {
      "blue": {
        "adjustPoints": 0,
        "autoCellPoints": 20,
        "autoCellsBottom": 1,
        "autoCellsInner": 1,
        "autoCellsOuter": 3,
        "autoInitLinePoints": 15,
        "autoPoints": 35,
        "controlPanelPoints": 0,
        "endgamePoints": 15,
        "endgameRobot1": "Park",
        "endgameRobot2": "Park",
        "endgameRobot3": "Park",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 0,
        "initLineRobot1": "Exited",
        "initLineRobot2": "Exited",
        "initLineRobot3": "Exited",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": true,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 1,
        "teleopCellPoints": 36,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 2,
        "teleopCellsOuter": 15,
        "teleopPoints": 51,
        "totalPoints": 86
      },
      "red": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 0,
        "autoPoints": 0,
        "controlPanelPoints": 0,
        "endgamePoints": 15,
        "endgameRobot1": "Park",
        "endgameRobot2": "Park",
        "endgameRobot3": "Park",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 15,
        "initLineRobot1": "None",
        "initLineRobot2": "None",
        "initLineRobot3": "None",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": false,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 8,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 4,
        "teleopPoints": 23,
        "totalPoints": 38
      }
    },
    "set_number": 2,
    "time": 1581792360,
    "videos": [
      {
        "key": "-Z3Isqo7esc",
        "type": "youtube"
      }
    ],
    "winning_alliance": "blue"
  },
  {
    "actual_time": 1581795097,
    "alliances": {
      "blue": {
        "dq_team_keys": [],
        "score": 101,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc3117",
          "frc4041",
          "frc501"
        ]
      },
      "red": {
        "dq_team_keys": [],
        "score": 38,
        "surrogate_team_keys": [],
        "team_keys": [
          "frc1073",
          "frc811",
          "frc58"
        ]
      }
    },
    "comp_level": "sf",
    "event_key": "2020week0",
    "key": "2020week0_sf2m2",
    "match_number": 2,
    "post_result_time": 1581795292,
    "predicted_time": 1581795064,
    "score_breakdown": {
      "blue": {
        "adjustPoints": 0,
        "autoCellPoints": 22,
        "autoCellsBottom": 0,
        "autoCellsInner": 3,
        "autoCellsOuter": 1,
        "autoInitLinePoints": 15,
        "autoPoints": 37,
        "controlPanelPoints": 0,
        "endgamePoints": 50,
        "endgameRobot1": "Park",
        "endgameRobot2": "Park",
        "endgameRobot3": "Hang",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 1,
        "foulPoints": 0,
        "initLineRobot1": "Exited",
        "initLineRobot2": "Exited",
        "initLineRobot3": "Exited",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": true,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 1,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 14,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 0,
        "teleopCellsOuter": 7,
        "teleopPoints": 64,
        "totalPoints": 101
      },
      "red": {
        "adjustPoints": 0,
        "autoCellPoints": 0,
        "autoCellsBottom": 0,
        "autoCellsInner": 0,
        "autoCellsOuter": 0,
        "autoInitLinePoints": 0,
        "autoPoints": 0,
        "controlPanelPoints": 0,
        "endgamePoints": 15,
        "endgameRobot1": "Park",
        "endgameRobot2": "Park",
        "endgameRobot3": "Park",
        "endgameRungIsLevel": "IsLevel",
        "foulCount": 0,
        "foulPoints": 3,
        "initLineRobot1": "None",
        "initLineRobot2": "None",
        "initLineRobot3": "None",
        "rp": 0,
        "shieldEnergizedRankingPoint": false,
        "shieldOperationalRankingPoint": false,
        "stage1Activated": true,
        "stage2Activated": false,
        "stage3Activated": false,
        "stage3TargetColor": "Unknown",
        "tba_numRobotsHanging": 0,
        "tba_shieldEnergizedRankingPointFromFoul": false,
        "techFoulCount": 0,
        "teleopCellPoints": 20,
        "teleopCellsBottom": 0,
        "teleopCellsInner": 2,
        "teleopCellsOuter": 7,
        "teleopPoints": 35,
        "totalPoints": 38
      }
    },
    "set_number": 2,
    "time": 1581793200,
    "videos": [
      {
        "key": "0Y6FAR-ly5w",
        "type": "youtube"
      }
    ],
    "winning_alliance": "blue"
  }
];

export const compLevels = {
    test: 0, // test match
    pm: 1, //practice match
    qm: 2, //qualification match
    ef: 3, //eighth finals
    qf: 4, //quarter finals
    sf: 5, //semi finals
    f: 6,  //finals
};

export const sortedMatches = Matches.sort((a, b) => {
    if (compLevels[a.comp_level] !== compLevels[b.comp_level]) {
        return compLevels[a.comp_level] - compLevels[b.comp_level]
    }
    if (a.set_number !== b.set_number) {
        return a.set_number - b.set_number
    }
    if (a.match_number !== b.match_number) {
        return a.match_number - b.match_number
    }
});



