//Source: https://www.thebluealliance.com/api/v3/event/2020week0/teams
// export const Teams = [
// 	{
// 		address: null,
// 		city: 'Hollis',
// 		country: 'USA',
// 		gmaps_place_id: null,
// 		gmaps_url: null,
// 		home_championship: null,
// 		key: 'frc1073',
// 		lat: null,
// 		lng: null,
// 		location_name: null,
// 		motto: null,
// 		name: 'Hollis Brookline High School/BAE Systems/Tucker Engineering Inc/Waters Corp&Hollis Brookline High School',
// 		nickname: 'The Force Team',
// 		postal_code: '03049',
// 		rookie_year: 2003,
// 		school_name: 'Hollis Brookline High School',
// 		state_prov: 'New Hampshire',
// 		team_number: 1073,
// 		website: 'http://www.frc1073.org'
// 	},
// 	{
// 		address: null,
// 		city: 'Walpole',
// 		country: 'USA',
// 		gmaps_place_id: null,
// 		gmaps_url: null,
// 		home_championship: null,
// 		key: 'frc1153',
// 		lat: null,
// 		lng: null,
// 		location_name: null,
// 		motto: null,
// 		name: 'The Gallivan Family / Dale Tool & Die / Merrikin Engineering / Waters Corporation / RiverTaw & Walpole High School',
// 		nickname: 'The Revolution',
// 		postal_code: '02081',
// 		rookie_year: 2003,
// 		school_name: 'Walpole High School',
// 		state_prov: 'Massachusetts',
// 		team_number: 1153,
// 		website: 'http://www.walpolerobotics.org/'
// 	},
// 	{
// 		address: null,
// 		city: 'Nashua',
// 		country: 'USA',
// 		gmaps_place_id: null,
// 		gmaps_url: null,
// 		home_championship: null,
// 		key: 'frc151',
// 		lat: null,
// 		lng: null,
// 		location_name: null,
// 		motto: null,
// 		name: 'MakeIt Labs/GHO Ventures/BAE Systems/3rd Degree Safety Solutions/Parker Hannifin/Star Machines/Ritz Carlton Boston/The Godfrey Hotel/Corning Foundation&Nashua High School-South&Nashua High School-North&Family/Community',
// 		nickname: 'Tough Techs',
// 		postal_code: '03062',
// 		rookie_year: 1992,
// 		school_name: 'Family/Community & Nashua High School-North & Nashua High School-South',
// 		state_prov: 'New Hampshire',
// 		team_number: 151,
// 		website: 'http://www.nashua151.org'
// 	},
// 	{
// 		team_number: 1519,
// 		city: 'currently meeting in Bedford',
// 		country: 'USA',
// 		key: 'frc1519',
// 		name: 'BAE Systems/Rockwell Automation/Cirtronics/Vertex&Milford Area Youth Homeschoolers Enriching Minds',
// 		nickname: 'Mechanical Mayhem',
// 		postal_code: '03055',
// 		rookie_year: 2005,
// 		school_name: 'Milford Area Youth Homeschoolers Enriching Minds',
// 		state_prov: 'New Hampshire',
//
// 		website: 'http://www.mechanicalmayhem.org/'
// 	},
// 	{
// 		address: null,
// 		city: 'Marlborough',
// 		country: 'USA',
// 		gmaps_place_id: null,
// 		gmaps_url: null,
// 		home_championship: null,
// 		key: 'frc157',
// 		lat: null,
// 		lng: null,
// 		location_name: null,
// 		motto: null,
// 		name: 'Boston Scientific/NASA/Entwistle/Raytheon/Avidia Bank&Assabet Valley Reg Tech HS',
// 		nickname: 'AZTECHS',
// 		postal_code: '01752',
// 		rookie_year: 1992,
// 		school_name: 'Assabet Valley Reg Tech HS',
// 		state_prov: 'Massachusetts',
// 		team_number: 157,
// 		website: 'http://www.aztechs157.org'
// 	},
// 	{
// 		address: null,
// 		city: 'Concord',
// 		country: 'USA',
// 		gmaps_place_id: null,
// 		gmaps_url: null,
// 		home_championship: null,
// 		key: 'frc1721',
// 		lat: null,
// 		lng: null,
// 		location_name: null,
// 		motto: null,
// 		name: "Bendrite/Concord Co-op/Molly B Foundation/Who Doesn't Want That?/BAE Systems/Spain Family/Boston Scientific & Concord Christian Academy & Concord High School",
// 		nickname: 'Tidal Force',
// 		postal_code: '03301',
// 		rookie_year: 2006,
// 		school_name: 'Concord High School',
// 		state_prov: 'New Hampshire',
// 		team_number: 1721,
// 		website: 'http://www.frc1721.org/'
// 	},
// 	{
// 		address: null,
// 		city: 'Peterborough',
// 		country: 'USA',
// 		gmaps_place_id: null,
// 		gmaps_url: null,
// 		home_championship: null,
// 		key: 'frc1729',
// 		lat: null,
// 		lng: null,
// 		location_name: null,
// 		motto: null,
// 		name: 'New Hampshire 4-H Association/NASA/William H. Wildes General Contracting LLC/Signature Smiles Dental/Anonymous Donor&Monadnock 4-H Robotics Club',
// 		nickname: 'Team Inconceivable!',
// 		postal_code: '03458',
// 		rookie_year: 2006,
// 		school_name: 'Monadnock 4-H Robotics Club',
// 		state_prov: 'New Hampshire',
// 		team_number: 1729,
// 		website: 'http://www.team1729.org'
// 	},
// 	{
// 		address: null,
// 		city: 'Franklin',
// 		country: 'USA',
// 		gmaps_place_id: null,
// 		gmaps_url: null,
// 		home_championship: null,
// 		key: 'frc2079',
// 		lat: null,
// 		lng: null,
// 		location_name: null,
// 		motto: null,
// 		name: 'United Technologies, Pratt & Whitney/Acorn Animal Hospital/Electric Time/4-H of Massachusetts & 4-H ALARM Robotics 2079',
// 		nickname: '4H ALARM Robotics',
// 		postal_code: '02038',
// 		rookie_year: 2007,
// 		school_name: '4-H ALARM Robotics 2079',
// 		state_prov: 'Massachusetts',
// 		team_number: 2079,
// 		website: 'http://www.alarmrobotics.com'
// 	},
// 	{
// 		address: null,
// 		city: 'Manchester',
// 		country: 'USA',
// 		gmaps_place_id: null,
// 		gmaps_url: null,
// 		home_championship: null,
// 		key: 'frc2084',
// 		lat: null,
// 		lng: null,
// 		location_name: null,
// 		motto: null,
// 		name: 'Spaulding Education Fund / The Hooper Fund / Manchester Masons / MIT Lincoln Lab / Pinpoint Laser Systems / Cape Ann Savings Bank / Lee Spence / Polaris & Manchester Essex Reg Middle HS',
// 		nickname: 'Robots by the C',
// 		postal_code: '01944',
// 		rookie_year: 2007,
// 		school_name: 'Manchester Essex Reg Middle HS',
// 		state_prov: 'Massachusetts',
// 		team_number: 2084,
// 		website: 'http:///www.robotsbythec.com'
// 	},
// 	{
// 		address: null,
// 		city: 'Nashua',
// 		country: 'USA',
// 		gmaps_place_id: null,
// 		gmaps_url: null,
// 		home_championship: null,
// 		key: 'frc2342',
// 		lat: null,
// 		lng: null,
// 		location_name: null,
// 		motto: null,
// 		name: 'Academy for Science and Design/BeyondTrust/4-H/C&M Machine Products/East Penn/Abbott Labs/amazon robotics/Raytheon/Analog Devices/Solidworks/Hi-Tech Fabricators/EmbroidMe/Actex Learning/Goffstown Ace Hardware/BAE SYSTEMS/Market Basket/Greater Nashua FIRST Robotics, Inc.&Neighborhood Group&4-H',
// 		nickname: 'Team Phoenix',
// 		postal_code: '03064',
// 		rookie_year: 2008,
// 		school_name: 'Neighborhood Group',
// 		state_prov: 'New Hampshire',
// 		team_number: 2342,
// 		website: 'http://team2342.org/'
// 	},
// 	{
// 		address: null,
// 		city: 'Manchester',
// 		country: 'USA',
// 		gmaps_place_id: null,
// 		gmaps_url: null,
// 		home_championship: null,
// 		key: 'frc238',
// 		lat: null,
// 		lng: null,
// 		location_name: null,
// 		motto: null,
// 		name: 'Bosch&Manchester Memorial High Sch',
// 		nickname: 'Crusaders',
// 		postal_code: '03103',
// 		rookie_year: 1999,
// 		school_name: 'Manchester Memorial High Sch',
// 		state_prov: 'New Hampshire',
// 		team_number: 238,
// 		website: 'http://frc238.org/'
// 	},
// 	{
// 		address: null,
// 		city: 'Boston',
// 		country: 'USA',
// 		gmaps_place_id: null,
// 		gmaps_url: null,
// 		home_championship: null,
// 		key: 'frc246',
// 		lat: null,
// 		lng: null,
// 		location_name: null,
// 		motto: null,
// 		name: 'Boston University & Boston University Academy',
// 		nickname: 'Overclocked',
// 		postal_code: '02215',
// 		rookie_year: 1999,
// 		school_name: 'Boston University Academy',
// 		state_prov: 'Massachusetts',
// 		team_number: 246,
// 		website: 'http://www.bu.edu/bufirst/'
// 	},
// 	{
// 		address: null,
// 		city: 'Melrose',
// 		country: 'USA',
// 		gmaps_place_id: null,
// 		gmaps_url: null,
// 		home_championship: null,
// 		key: 'frc2713',
// 		lat: null,
// 		lng: null,
// 		location_name: null,
// 		motto: null,
// 		name: 'Citizens of Melrose/Melrose Bank Foundation/Salesforce.com/BAE Systems/Raytheon/Churchill Corp/SAME&Melrose High School',
// 		nickname: 'iRaiders',
// 		postal_code: '02176',
// 		rookie_year: 2009,
// 		school_name: 'Melrose High School',
// 		state_prov: 'Massachusetts',
// 		team_number: 2713,
// 		website: 'http:///www.iraiders.org'
// 	},
// 	{
// 		address: null,
// 		city: 'Montreal',
// 		country: 'Canada',
// 		gmaps_place_id: null,
// 		gmaps_url: null,
// 		home_championship: null,
// 		key: 'frc296',
// 		lat: null,
// 		lng: null,
// 		location_name: null,
// 		motto: null,
// 		name: 'RBC Wealth Management PH&N Investment Counsel&Loyola High School&Sacred Heart',
// 		nickname: 'Northern Knights',
// 		postal_code: 'H4B 1R2',
// 		rookie_year: 1999,
// 		school_name: 'Loyola High School & Sacred Heart',
// 		state_prov: 'Québec',
// 		team_number: 296,
// 		website: 'http://robotics.loyola.ca'
// 	},
// 	{
// 		address: null,
// 		city: 'Sherbrooke',
// 		country: 'Canada',
// 		gmaps_place_id: null,
// 		gmaps_url: null,
// 		home_championship: null,
// 		key: 'frc3117',
// 		lat: null,
// 		lng: null,
// 		location_name: null,
// 		motto: null,
// 		name: 'Bombardier Aéronautique/Université de Sherbrooke/BRP/24 juin/CSRS Fondation/UTC/M.I. Integration/BRP&Triolet',
// 		nickname: 'Harfangs',
// 		postal_code: 'j1k2x6',
// 		rookie_year: 2009,
// 		school_name: 'Triolet',
// 		state_prov: 'Québec',
// 		team_number: 3117,
// 		website: 'http://www.firstinspires.org/'
// 	},
// 	{
// 		address: null,
// 		city: 'Litchfield',
// 		country: 'USA',
// 		gmaps_place_id: null,
// 		gmaps_url: null,
// 		home_championship: null,
// 		key: 'frc3323',
// 		lat: null,
// 		lng: null,
// 		location_name: null,
// 		motto: null,
// 		name: 'Litchfield School District/New Hampshire Department of Education/FIRST Corporate Sponsor/FWM Inc./Schneider Electric/Getinge/BAE Systems/AIS/Hubbell/Parker-Hannifin/Precision Model Fab&Campbell High School',
// 		nickname: 'Potential Energy',
// 		postal_code: '03052',
// 		rookie_year: 2010,
// 		school_name: 'Campbell High School',
// 		state_prov: 'New Hampshire',
// 		team_number: 3323,
// 		website: 'http://www.pe3323.com'
// 	},
// 	{
// 		address: null,
// 		city: 'Windham',
// 		country: 'USA',
// 		gmaps_place_id: null,
// 		gmaps_url: null,
// 		home_championship: null,
// 		key: 'frc3467',
// 		lat: null,
// 		lng: null,
// 		location_name: null,
// 		motto: null,
// 		name: 'Veloxion, Inc./Windham High School/Analog Devices/BAE Systems&Windup Robotics 4-H Club',
// 		nickname: 'Windham Windup',
// 		postal_code: '03087',
// 		rookie_year: 2011,
// 		school_name: 'Windup Robotics 4-H Club',
// 		state_prov: 'New Hampshire',
// 		team_number: 3467,
// 		website: 'https://www.team3467.org'
// 	},
// 	{
// 		address: null,
// 		city: 'Saint-Laurent',
// 		country: 'Canada',
// 		gmaps_place_id: null,
// 		gmaps_url: null,
// 		home_championship: null,
// 		key: 'frc3986',
// 		lat: null,
// 		lng: null,
// 		location_name: null,
// 		motto: null,
// 		name: 'Banque Nationale Canada/Bombardier/CSMB/Microsoft/MotionCorrect/MDA/CAE&École secondaire Saint-Laurent',
// 		nickname: 'Express-O',
// 		postal_code: 'H4R1T4',
// 		rookie_year: 2012,
// 		school_name: 'École secondaire Saint-Laurent',
// 		state_prov: 'Québec',
// 		team_number: 3986,
// 		website: 'http://www.express-o.ca'
// 	},
// 	{
// 		address: null,
// 		city: 'Gardiner',
// 		country: 'USA',
// 		gmaps_place_id: null,
// 		gmaps_url: null,
// 		home_championship: null,
// 		key: 'frc4041',
// 		lat: null,
// 		lng: null,
// 		location_name: null,
// 		motto: null,
// 		name: 'MSAD #11 / The Robinson Fund / TRC Engineering / Abilis Solutions / Robotics Institute of Maine & Gardiner Area High School',
// 		nickname: 'Iron Tigers',
// 		postal_code: '04345',
// 		rookie_year: 2012,
// 		school_name: 'Gardiner Area High School',
// 		state_prov: 'Maine',
// 		team_number: 4041,
// 		website: 'http://www.firstteam4041.com'
// 	},
// 	{
// 		address: null,
// 		city: 'Ayer',
// 		country: 'USA',
// 		gmaps_place_id: null,
// 		gmaps_url: null,
// 		home_championship: null,
// 		key: 'frc4905',
// 		lat: null,
// 		lng: null,
// 		location_name: null,
// 		motto: null,
// 		name: 'Boston Scientific/Schneider Electric/Analog Devices/Johnson Controls/BAE Systems/SOLIDWORKS/Polymershapes/Christine Miska&AYER SHIRLEY REGIONAL HIGH SCHOOL',
// 		nickname: 'Andromeda One',
// 		postal_code: '01432',
// 		rookie_year: 2014,
// 		school_name: 'AYER SHIRLEY REGIONAL HIGH SCHOOL',
// 		state_prov: 'Massachusetts',
// 		team_number: 4905,
// 		website: 'https://frc4905.com/'
// 	},
// 	{
// 		address: null,
// 		city: 'Billerica',
// 		country: 'USA',
// 		gmaps_place_id: null,
// 		gmaps_url: null,
// 		home_championship: null,
// 		key: 'frc4909',
// 		lat: null,
// 		lng: null,
// 		location_name: null,
// 		motto: null,
// 		name: 'NASA/Analog Devices/BTU International/Raytheon/MRSI Systems&Billerica Memorial High School',
// 		nickname: 'Bionics',
// 		postal_code: '01821',
// 		rookie_year: 2014,
// 		school_name: 'Billerica Memorial High School',
// 		state_prov: 'Massachusetts',
// 		team_number: 4909,
// 		website: 'http://www.team4909.org/'
// 	},
// 	{
// 		address: null,
// 		city: 'Manchester',
// 		country: 'USA',
// 		gmaps_place_id: null,
// 		gmaps_url: null,
// 		home_championship: null,
// 		key: 'frc501',
// 		lat: null,
// 		lng: null,
// 		location_name: null,
// 		motto: null,
// 		name: 'AC Trust/Stu, Sam & Lexxie/Louis P. Cote Inc./Geneia/Liberty Utilities/New Hampshire Stamping Co&4-H&Goffstown High School&Manchester High School-West',
// 		nickname: 'The PowerKnights',
// 		postal_code: '03101',
// 		rookie_year: 2001,
// 		school_name: '4-H & Manchester High School-West & Goffstown High School',
// 		state_prov: 'New Hampshire',
// 		team_number: 501,
// 		website: 'http://powerknights.com'
// 	},
// 	{
// 		address: null,
// 		city: 'Portland',
// 		country: 'USA',
// 		gmaps_place_id: null,
// 		gmaps_url: null,
// 		home_championship: null,
// 		key: 'frc5687',
// 		lat: null,
// 		lng: null,
// 		location_name: null,
// 		motto: null,
// 		name: 'Baxter Academy Tech & Science',
// 		nickname: 'The Outliers',
// 		postal_code: '04101',
// 		rookie_year: 2015,
// 		school_name: 'Baxter Academy Tech & Science',
// 		state_prov: 'Maine',
// 		team_number: 5687,
// 		website: 'http://www.firstinspires.org/'
// 	},
// 	{
// 		address: null,
// 		city: 'South Portland',
// 		country: 'USA',
// 		gmaps_place_id: null,
// 		gmaps_url: null,
// 		home_championship: null,
// 		key: 'frc58',
// 		lat: null,
// 		lng: null,
// 		location_name: null,
// 		motto: null,
// 		name: 'South Portland School Department/Robotics Institute of Maine/Building STEAM&South Portland High School',
// 		nickname: 'The Riot Crew',
// 		postal_code: '04106',
// 		rookie_year: 1996,
// 		school_name: 'South Portland High School',
// 		state_prov: 'Maine',
// 		team_number: 58,
// 		website: 'http://www.riotcrew.net'
// 	},
// 	{
// 		address: null,
// 		city: 'Concord',
// 		country: 'USA',
// 		gmaps_place_id: null,
// 		gmaps_url: null,
// 		home_championship: null,
// 		key: 'frc5813',
// 		lat: null,
// 		lng: null,
// 		location_name: null,
// 		motto: null,
// 		name: 'AAVID, Thermal Divsion of Boyd Corporation/FIRST in NH/Murali Ravel, DMD PC/BAE ES/SOLIDWORKS&Neighborhood Group',
// 		nickname: 'Morpheus',
// 		postal_code: '03301',
// 		rookie_year: 2016,
// 		school_name: 'Neighborhood Group',
// 		state_prov: 'New Hampshire',
// 		team_number: 5813,
// 		website: 'https://5813.frc.team'
// 	},
// 	{
// 		address: null,
// 		city: 'Lowell',
// 		country: 'USA',
// 		gmaps_place_id: null,
// 		gmaps_url: null,
// 		home_championship: null,
// 		key: 'frc5962',
// 		lat: null,
// 		lng: null,
// 		location_name: null,
// 		motto: null,
// 		name: 'UMASS Lowell/Merrimack Valley Robotics/Best Buy/Analog Devices/Boston Scientific/NOKIA Bell Labs/Juniper Networks/IBM/BAE Systems/Precision Manufacturing/Apex Tool Group/L3 Harris/Colonial Electronic Manufacturers/Kronos/TE Connectivity/NE BioLabs/Teradyne/Carbon Colors/Fisher Unitech/Primo Pizza, Dracut & Family/Community',
// 		nickname: 'perSEVERE',
// 		postal_code: '01853',
// 		rookie_year: 2016,
// 		school_name: 'Family/Community',
// 		state_prov: 'Massachusetts',
// 		team_number: 5962,
// 		website: 'https://frcpersevere.com'
// 	},
// 	{
// 		address: null,
// 		city: 'Nashua',
// 		country: 'USA',
// 		gmaps_place_id: null,
// 		gmaps_url: null,
// 		home_championship: null,
// 		key: 'frc811',
// 		lat: null,
// 		lng: null,
// 		location_name: null,
// 		motto: null,
// 		name: 'State of New Hampshire/Raytheon IDS/BAE SYSTEMS/MILL5/NASA&Bishop Guertin High School',
// 		nickname: 'Cardinals',
// 		postal_code: '03060',
// 		rookie_year: 2002,
// 		school_name: 'Bishop Guertin High School',
// 		state_prov: 'New Hampshire',
// 		team_number: 811,
// 		website: 'http://www.team811.com'
// 	}
// ];

export const TeamSort = (a, b) => {
	return a.team_number - b.team_number;
};

// export const sortedTeams = Teams.sort();
