name: Development Build

on:
  workflow_dispatch:
  push:
    branches: # branches to run builds on
      - 'main'
      - 'master'
    paths-ignore: # do not run if these are the only files that have changed
      - README.md
      - .gitignore
      - docs/**
      - tools/**

jobs:
  development-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install NPM Deps
        run: |
          npm ci

      - name: Build Svelte App
        run: |
          npm run build

      - name: Copy built assets to android folder
        run: |
          npx cap sync

      - name: Set up our JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Decode Keystore
        run: |
          which base64
          command base64
          echo "${{ secrets.SIGNING_KEYSTORE_B64 }}" | base64 -d > keystore.jks

      - name: Build App
        run: |
          cd android
          ./gradlew bundleRelease

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: app/build/outputs/